// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqgPtes2eKOliK0ESC6NxbmnaGptyx7Oc',
    appId: '1:1098081256141:web:dbe7e30eb00654a7741f84',
    messagingSenderId: '1098081256141',
    projectId: 'umkm-store-9f3cb',
    authDomain: 'umkm-store-9f3cb.firebaseapp.com',
    storageBucket: 'umkm-store-9f3cb.appspot.com',
    measurementId: 'G-FD70F9KXP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2jGmyVMQJmXVDOTUN-WxGwGLveblbigM',
    appId: '1:1098081256141:android:063816083569681e741f84',
    messagingSenderId: '1098081256141',
    projectId: 'umkm-store-9f3cb',
    storageBucket: 'umkm-store-9f3cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALPVTjqke7T36txciDr4zGlkgVQ8XW8_U',
    appId: '1:1098081256141:ios:a9674485239b5475741f84',
    messagingSenderId: '1098081256141',
    projectId: 'umkm-store-9f3cb',
    storageBucket: 'umkm-store-9f3cb.appspot.com',
    iosBundleId: 'com.example.umkmStoreApk3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALPVTjqke7T36txciDr4zGlkgVQ8XW8_U',
    appId: '1:1098081256141:ios:23f37f4d7d189485741f84',
    messagingSenderId: '1098081256141',
    projectId: 'umkm-store-9f3cb',
    storageBucket: 'umkm-store-9f3cb.appspot.com',
    iosBundleId: 'com.example.umkmStoreApk3.RunnerTests',
  );
}
